apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 30s
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
        editable: true
        jsonData:
          maxLines: 1000 