apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: monitoring
data:
  alerts.yaml: |
    groups:
      - name: error_alerts
        rules:
          - alert: HighErrorRate
            expr: |
              sum(rate({app=~".+"} |~ "(?i)error|exception|fail|fatal" [5m])) by (app)
              > 10
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High error rate in {{ $labels.app }}
              description: Error rate is above 10 per minute in {{ $labels.app }}

          - alert: CriticalError
            expr: |
              sum(rate({app=~".+"} |~ "(?i)fatal|panic|critical" [5m])) by (app)
              > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: Critical error detected in {{ $labels.app }}
              description: Critical error found in logs for {{ $labels.app }}

      - name: kubernetes_alerts
        rules:
          - alert: PodCrashLooping
            expr: |
              count_over_time({app=~".+", container!=""} |~ "Back-off restarting failed container" [5m])
              > 0
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: Pod crash looping detected
              description: Container in pod is crash looping

          - alert: KubernetesNodeNotReady
            expr: |
              count_over_time({job="kubernetes-nodes"} |~ "Node .* condition Ready changed from True to False" [5m])
              > 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: Kubernetes node not ready
              description: A node has become unready

      - name: aiops_alerts
        rules:
          - alert: AIModelPredictionError
            expr: |
              sum(rate({app=~"aiops-.*"} |~ "(?i)prediction.*error|model.*fail" [5m])) by (app)
              > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: AI model prediction errors in {{ $labels.app }}
              description: AI/ML model is experiencing prediction errors

          - alert: AnomalyDetectionError
            expr: |
              sum(rate({app=~"aiops-.*"} |~ "(?i)anomaly.*detection.*fail|outlier.*error" [5m])) by (app)
              > 0
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: Anomaly detection errors in {{ $labels.app }}
              description: Anomaly detection system is experiencing errors

      - name: system_alerts
        rules:
          - alert: DiskSpaceRunningLow
            expr: |
              count_over_time({job="kubernetes-nodes"} |~ "(?i)no space left|disk.*full" [5m])
              > 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: Disk space running low
              description: System is reporting low disk space issues

          - alert: HighMemoryUsage
            expr: |
              count_over_time({job="kubernetes-nodes"} |~ "(?i)out of memory|oom killer" [5m])
              > 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: High memory usage detected
              description: System is experiencing memory pressure

  recording.yaml: |
    groups:
      - name: error_rates
        rules:
          - record: error_rate:by_app
            expr: |
              sum(rate({app=~".+"} |~ "(?i)error|exception|fail" [5m])) by (app)

          - record: critical_error_rate:by_app
            expr: |
              sum(rate({app=~".+"} |~ "(?i)fatal|panic|critical" [5m])) by (app)

      - name: aiops_metrics
        rules:
          - record: aiops_prediction_error_rate
            expr: |
              sum(rate({app=~"aiops-.*"} |~ "(?i)prediction.*error|model.*fail" [5m])) by (app)

          - record: aiops_anomaly_detection_rate
            expr: |
              sum(rate({app=~"aiops-.*"} |~ "(?i)anomaly.*detection.*fail|outlier.*error" [5m])) by (app) 