apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alerts.yml: |
    groups:
      - name: node_alerts
        rules:
          - alert: HighCPUUsage
            expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High CPU usage on {{ $labels.instance }}
              description: CPU usage is above 80% for 5 minutes

          - alert: HighMemoryUsage
            expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High memory usage on {{ $labels.instance }}
              description: Memory usage is above 85% for 5 minutes

      - name: kubernetes_alerts
        rules:
          - alert: KubernetesPodCrashLooping
            expr: rate(kube_pod_container_status_restarts_total[15m]) * 60 * 5 > 0
            for: 15m
            labels:
              severity: warning
            annotations:
              summary: Kubernetes Pod crash looping (instance {{ $labels.instance }})
              description: Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping

          - alert: KubernetesNodeNotReady
            expr: kube_node_status_condition{condition="Ready",status="true"} == 0
            for: 10m
            labels:
              severity: critical
            annotations:
              summary: Kubernetes Node not ready (instance {{ $labels.instance }})
              description: Node {{ $labels.node }} has been unready for more than 10 minutes

  recording.yml: |
    groups:
      - name: node_recording_rules
        rules:
          - record: node:cpu:usage_percentage
            expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)

          - record: node:memory:usage_percentage
            expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100

      - name: kubernetes_recording_rules
        rules:
          - record: kubernetes:pod:restart_rate
            expr: rate(kube_pod_container_status_restarts_total[15m])

          - record: kubernetes:pod:ready_percentage
            expr: sum(kube_pod_status_ready{condition="true"}) / sum(kube_pod_status_ready) * 100 