version: '3.8'

services:
  # ML-анализатор
  analyzer:
    build:
      context: .
      dockerfile: docker/analyzer/Dockerfile
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - LOG_LEVEL=debug
    ports:
      - "8080:8080"
    depends_on:
      - prometheus

  # Оркестратор
  orchestrator:
    build:
      context: .
      dockerfile: docker/orchestrator/Dockerfile
    environment:
      - ANALYZER_URL=http://analyzer:8080
      - LOG_LEVEL=debug
    ports:
      - "8081:8081"
    depends_on:
      - analyzer

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: unless-stopped

  # Grafana
  grafana:
    image: grafana/grafana:10.0.3
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped

  # Loki
  loki:
    image: grafana/loki:2.8.4
    volumes:
      - ./loki:/etc/loki
      - loki_data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    restart: unless-stopped

  # Promtail
  promtail:
    image: grafana/promtail:2.8.4
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.47
    ports:
      - "16686:16686"
      - "14250:14250"

  otel-collector:
    image: otel/opentelemetry-collector:0.81.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector:/etc/otel-collector
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Health check

volumes:
  prometheus_data:
  grafana_data:
  loki_data: 