---
# charts/ai-module/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ai-module
spec:
  selector:
    app: ai-module
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: ClusterIP
