name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Install dependencies
        run: go mod download
        
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          
      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push analyzer
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/analyzer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aiops-analyzer:latest
          
      - name: Build and push orchestrator
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/orchestrator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aiops-orchestrator:latest 